# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "jan24app"
client_id = "4f03fb9dec0cf4926b2202b92dea5593"
application_url = "https://equally-main-giraffe.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://equally-main-giraffe.ngrok-free.app/auth",
  "https://equally-main-giraffe.ngrok-free.app/authenticate"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "dec23store.myshopify.com"
